.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH SQ 1 0.28.0 Sequoia-PGP "User Commands"
.SH NAME
sq autocrypt encode\-sender \- Encodes a certificate into an Autocrypt header
.SH SYNOPSIS
.br
\fBsq\fR [\fIGLOBAL OPTIONS\fR] \fBautocrypt encode\-sender\fR [\fIOPTIONS\fR] \fIFILE\fR
.SH DESCRIPTION
Encodes a certificate into an Autocrypt header.
.PP
A certificate can be encoded and included in a header of an email
message.  This command encodes the certificate, adds the senders email
address (which must match the one used in the "From" header), and the
senders "prefer\-encrypt" state (see the Autocrypt spec for more
information).
.PP
The converse operation is "sq autocrypt decode".
.PP


.SH OPTIONS
.SS "Global options"
.TP
\fB\-f\fR, \fB\-\-force\fR
Overwrites existing files
.TP
\fB\-\-help\fR
Print help information
.TP
\fB\-\-known\-notation\fR=\fINOTATION\fR
Adds NOTATION to the list of known notations
.TP
\fB\-\-output\-format\fR=\fIFORMAT\fR
Produces output in FORMAT, if possible
.TP
\fB\-\-output\-version\fR=\fIVERSION\fR
Produces output variant VERSION.
.TP
\fB\-\-version\fR
Print version information
.SS "Subcommand options"
.TP
\fB\-\-email\fR=\fIADDRESS\fR
Sets the address [default: primary userid]
.TP
\fB\-\-help\fR
Print help information
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Writes to FILE or stdout if omitted
.TP
\fB\-\-prefer\-encrypt\fR=\fIPREFER\-ENCRYPT\fR
Sets the prefer\-encrypt attribute
.TP
\fB\-\-version\fR
Print version information
.SH EXAMPLES
.PP

.PP
Encodes a certificate
.PP
.nf
.RS
sq autocrypt encode\-sender juliet.pgp
.RE
.fi
.PP

.PP
Encodes a certificate with an explicit sender address
.PP
.nf
.RS
sq autocrypt encode\-sender \-\-email juliet@example.org juliet.pgp
.RE
.fi
.PP

.PP
Encodes a certificate while indicating the willingness to encrypt
.PP
.nf
.RS
sq autocrypt encode\-sender \-\-prefer\-encrypt mutual juliet.pgp
.RE
.fi
.SH "SEE ALSO"
.nh
\fBsq\fR(1).
.hy
.PP
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.SH VERSION
0.28.0 (sequoia\-openpgp 1.13.0, using Nettle)
