.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH SQ 1 0.28.0 Sequoia-PGP "User Commands"
.SH NAME
sq certify \- Certifies a User ID for a Certificate
.SH SYNOPSIS
.br
\fBsq\fR [\fIGLOBAL OPTIONS\fR] \fBcertify\fR [\fIOPTIONS\fR] \fICERTIFIER\-KEY\fR \fICERTIFICATE\fR \fIUSERID\fR
.SH DESCRIPTION
Certifies a User ID for a Certificate.
.PP
Using a certification a keyholder may vouch for the fact that another
certificate legitimately belongs to a user id.  In the context of
emails this means that the same entity controls the key and the email
address.  These kind of certifications form the basis for the Web Of
Trust.
.PP
This command emits the certificate with the new certification.  The
updated certificate has to be distributed, preferably by sending it to
the certificate holder for attestation.  See also "sq key
attest\-certification".
.PP


.SH OPTIONS
.SS "Global options"
.TP
\fB\-f\fR, \fB\-\-force\fR
Overwrites existing files
.TP
\fB\-\-help\fR
Print help information
.TP
\fB\-\-known\-notation\fR=\fINOTATION\fR
Adds NOTATION to the list of known notations
.TP
\fB\-\-output\-format\fR=\fIFORMAT\fR
Produces output in FORMAT, if possible
.TP
\fB\-\-output\-version\fR=\fIVERSION\fR
Produces output variant VERSION.
.TP
\fB\-\-version\fR
Print version information
.SS "Subcommand options"
.TP
\fB\-B\fR, \fB\-\-binary\fR
Emits binary data
.TP
\fB\-a\fR, \fB\-\-amount\fR=\fITRUST_AMOUNT\fR
Sets the amount of trust
.TP
\fB\-\-allow\-not\-alive\-certifier\fR
Don\*(Aqt fail if the certificate making the certification is not alive.
.TP
\fB\-\-allow\-revoked\-certifier\fR
Don\*(Aqt fail if the certificate making the certification is revoked.
.TP
\fB\-d\fR, \fB\-\-depth\fR=\fITRUST_DEPTH\fR
Sets the trust depth
.TP
\fB\-\-expires\fR=\fITIME\fR
Makes the certification expire at TIME (as ISO 8601)
.TP
\fB\-\-expires\-in\fR=\fIDURATION\fR
Makes the certification expire after DURATION (as N[ymwds]) [default: 5y]
.TP
\fB\-\-help\fR
Print help information
.TP
\fB\-l\fR, \fB\-\-local\fR
Makes the certification a local certification
.TP
\fB\-\-non\-revocable\fR
Marks the certification as being non\-revocable
.TP
\fB\-\-notation\fR=\fINAME\fR
Adds a notation to the certification.
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Writes to FILE or stdout if omitted
.TP
\fB\-\-private\-key\-store\fR=\fIKEY_STORE\fR
Provides parameters for private key store
.TP
\fB\-r\fR, \fB\-\-regex\fR=\fIREGEX\fR
Adds a regular expression to constrain what a trusted introducer can certify
.TP
\fB\-\-time\fR=\fITIME\fR
Sets the certification time to TIME (as ISO 8601)
.TP
\fB\-\-version\fR
Print version information
.SH EXAMPLES
.PP

.PP
Juliet certifies that Romeo controls romeo.pgp and romeo@example.org
.PP
.nf
.RS
sq certify juliet.pgp romeo.pgp "<romeo@example.org>"
.RE
.fi
.SH "SEE ALSO"
.nh
\fBsq\fR(1).
.hy
.PP
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.SH VERSION
0.28.0 (sequoia\-openpgp 1.13.0, using Nettle)
