.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH SQ 1 0.28.0 Sequoia-PGP "User Commands"
.SH NAME
sq encrypt \- Encrypts a message
.SH SYNOPSIS
.br
\fBsq\fR [\fIGLOBAL OPTIONS\fR] \fBencrypt\fR [\fIOPTIONS\fR] \fIFILE\fR
.SH DESCRIPTION
Encrypts a message.
.PP
Encrypts a message for any number of recipients and with any number of
passwords, optionally signing the message in the process.
.PP
The converse operation is "sq decrypt".
.PP


.SH OPTIONS
.SS "Global options"
.TP
\fB\-f\fR, \fB\-\-force\fR
Overwrites existing files
.TP
\fB\-\-help\fR
Print help information
.TP
\fB\-\-known\-notation\fR=\fINOTATION\fR
Adds NOTATION to the list of known notations
.TP
\fB\-\-output\-format\fR=\fIFORMAT\fR
Produces output in FORMAT, if possible
.TP
\fB\-\-output\-version\fR=\fIVERSION\fR
Produces output variant VERSION.
.TP
\fB\-\-version\fR
Print version information
.SS "Subcommand options"
.TP
\fB\-B\fR, \fB\-\-binary\fR
Emits binary data
.TP
\fB\-\-compression\fR=\fIKIND\fR
Selects compression scheme to use
.TP
\fB\-\-help\fR
Print help information
.TP
\fB\-\-mode\fR=\fIMODE\fR
Selects what kind of keys are considered for encryption.
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Writes to FILE or stdout if omitted
.TP
\fB\-\-private\-key\-store\fR=\fIKEY_STORE\fR
Provides parameters for private key store
.TP
\fB\-\-recipient\-file\fR=\fICERT_RING_FILE\fR
Encrypts to all certificates in CERT_RING_FILE
.TP
\fB\-s\fR, \fB\-\-symmetric\fR
Adds a password to encrypt with
.TP
\fB\-\-signer\-file\fR=\fIKEY_FILE\fR
Signs the message using the key in KEY_FILE
.TP
\fB\-t\fR, \fB\-\-time\fR=\fITIME\fR
Chooses keys valid at the specified time and sets the signature\*(Aqs creation time
.TP
\fB\-\-use\-expired\-subkey\fR
Falls back to expired encryption subkeys
.TP
\fB\-\-version\fR
Print version information
.SH EXAMPLES
.PP

.PP
Encrypt a file using a certificate
.PP
.nf
.RS
sq encrypt \-\-recipient\-file romeo.pgp message.txt
.RE
.fi
.PP

.PP
Encrypt a file creating a signature in the process
.PP
.nf
.RS
sq encrypt \-\-recipient\-file romeo.pgp \-\-signer\-file juliet.pgp message.txt
.RE
.fi
.PP

.PP
Encrypt a file using a password
.PP
.nf
.RS
sq encrypt \-\-symmetric message.txt
.RE
.fi
.SH "SEE ALSO"
.nh
\fBsq\fR(1).
.hy
.PP
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.SH VERSION
0.28.0 (sequoia\-openpgp 1.13.0, using Nettle)
