.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH SQ 1 0.28.0 Sequoia-PGP "User Commands"
.SH NAME
sq keyring filter \- Joins keys into a keyring applying a filter
.SH SYNOPSIS
.br
\fBsq\fR [\fIGLOBAL OPTIONS\fR] \fBkeyring filter\fR [\fIOPTIONS\fR] \fIFILE\fR
.SH DESCRIPTION
Joins keys into a keyring applying a filter.
.PP
This can be used to filter keys based on given predicates,
e.g. whether they have a user id containing an email address with a
certain domain.  Additionally, the keys can be pruned to only include
components matching the predicates.
.PP
If no filters are supplied, everything matches.
.PP
If multiple predicates are given, they are or\*(Aqed, i.e. a key matches
if any of the predicates match.  To require all predicates to match,
chain multiple invocations of this command.  See EXAMPLES for
inspiration.
.PP


.SH OPTIONS
.SS "Global options"
.TP
\fB\-f\fR, \fB\-\-force\fR
Overwrites existing files
.TP
\fB\-\-help\fR
Print help information
.TP
\fB\-\-known\-notation\fR=\fINOTATION\fR
Adds NOTATION to the list of known notations
.TP
\fB\-\-output\-format\fR=\fIFORMAT\fR
Produces output in FORMAT, if possible
.TP
\fB\-\-output\-version\fR=\fIVERSION\fR
Produces output variant VERSION.
.TP
\fB\-\-version\fR
Print version information
.SS "Subcommand options"
.TP
\fB\-B\fR, \fB\-\-binary\fR
Emits binary data
.TP
\fB\-P\fR, \fB\-\-prune\-certs\fR
Removes certificate components not matching the filter
.TP
\fB\-\-domain\fR=\fIFQDN\fR
Matches on email domain FQDN
.TP
\fB\-\-email\fR=\fIADDRESS\fR
Matches on email ADDRESS
.TP
\fB\-\-handle\fR=\fIFINGERPRINT|KEYID\fR
Matches on (sub)key fingerprints and key ids
.TP
\fB\-\-help\fR
Print help information
.TP
\fB\-\-name\fR=\fINAME\fR
Matches on NAME
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Writes to FILE or stdout if omitted
.TP
\fB\-\-to\-cert\fR
Converts any keys in the input to certificates.  Converting a key to a certificate removes secret key material from the key thereby turning it into a certificate.
.TP
\fB\-\-userid\fR=\fIUSERID\fR
Matches on USERID
.TP
\fB\-\-version\fR
Print version information
.SH EXAMPLES
.PP

.PP
Converts a key to a cert (i.e., remove any secret key material)
.PP
.nf
.RS
sq keyring filter \-\-to\-cert cat juliet.pgp
.RE
.fi
.PP

.PP
Gets the keys with a user id on example.org
.PP
.nf
.RS
sq keyring filter \-\-domain example.org keys.pgp
.RE
.fi
.PP

.PP
Gets the keys with a user id on example.org or example.net
.PP
.nf
.RS
sq keyring filter \-\-domain example.org \-\-domain example.net keys.pgp
.RE
.fi
.PP

.PP
Gets the keys with a user id with the name Juliet
.PP
.nf
.RS
sq keyring filter \-\-name Juliet keys.pgp
.RE
.fi
.PP

.PP
Gets the keys with a user id with the name Juliet on example.org
.PP
.nf
.RS
sq keyring filter \-\-domain example.org keys.pgp | \\
.RE
.fi
.PP
  sq keyring filter \-\-name Juliet
.PP

.PP
Gets the keys with a user id on example.org, pruning other userids
.PP
.nf
.RS
sq keyring filter \-\-domain example.org \-\-prune\-certs certs.pgp
.RE
.fi
.SH "SEE ALSO"
.nh
\fBsq\fR(1).
.hy
.PP
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.SH VERSION
0.28.0 (sequoia\-openpgp 1.13.0, using Nettle)
