.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH SQ 1 0.28.0 Sequoia-PGP "User Commands"
.SH NAME
sq key extract\-cert \- Converts a key to a cert
.SH SYNOPSIS
.br
\fBsq\fR [\fIGLOBAL OPTIONS\fR] \fBkey extract\-cert\fR [\fIOPTIONS\fR] \fIFILE\fR
.SH DESCRIPTION
Converts a key to a cert.
.PP
After generating a key, use this command to get the certificate
corresponding to the key.  The key must be kept secure, while the
certificate should be handed out to correspondents, e.g. by uploading
it to a keyserver.
.PP


.SH OPTIONS
.SS "Global options"
.TP
\fB\-f\fR, \fB\-\-force\fR
Overwrites existing files
.TP
\fB\-\-help\fR
Print help information
.TP
\fB\-\-known\-notation\fR=\fINOTATION\fR
Adds NOTATION to the list of known notations
.TP
\fB\-\-output\-format\fR=\fIFORMAT\fR
Produces output in FORMAT, if possible
.TP
\fB\-\-output\-version\fR=\fIVERSION\fR
Produces output variant VERSION.
.TP
\fB\-\-version\fR
Print version information
.SS "Subcommand options"
.TP
\fB\-B\fR, \fB\-\-binary\fR
Emits binary data
.TP
\fB\-\-help\fR
Print help information
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Writes to FILE or stdout if omitted
.TP
\fB\-\-version\fR
Print version information
.SH EXAMPLES
.PP

.PP
First, this generates a key
.PP
.nf
.RS
sq key generate \-\-userid "<juliet@example.org>" \-\-export juliet.key.pgp
.RE
.fi
.PP

.PP
Then, this extracts the certificate for distribution
.PP
.nf
.RS
sq key extract\-cert \-\-output juliet.cert.pgp juliet.key.pgp
.RE
.fi
.SH "SEE ALSO"
.nh
\fBsq\fR(1).
.hy
.PP
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.SH VERSION
0.28.0 (sequoia\-openpgp 1.13.0, using Nettle)
