.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH SQ 1 0.28.0 Sequoia-PGP "User Commands"
.SH NAME
sq packet dump \- Lists packets
.SH SYNOPSIS
.br
\fBsq\fR [\fIGLOBAL OPTIONS\fR] \fBpacket dump\fR [\fIOPTIONS\fR] \fIFILE\fR
.SH DESCRIPTION
Lists packets.
.PP
Creates a human\-readable description of the packet sequence.
Additionally, it can print cryptographic artifacts, and print the raw
octet stream similar to hexdump(1), annotating specifically which
bytes are parsed into OpenPGP values.
.PP
To inspect encrypted messages, either supply the session key, or see
"sq decrypt \-\-dump" or "sq packet decrypt".
.PP


.SH OPTIONS
.SS "Global options"
.TP
\fB\-f\fR, \fB\-\-force\fR
Overwrites existing files
.TP
\fB\-\-help\fR
Print help information
.TP
\fB\-\-known\-notation\fR=\fINOTATION\fR
Adds NOTATION to the list of known notations
.TP
\fB\-\-output\-format\fR=\fIFORMAT\fR
Produces output in FORMAT, if possible
.TP
\fB\-\-output\-version\fR=\fIVERSION\fR
Produces output variant VERSION.
.TP
\fB\-\-version\fR
Print version information
.SS "Subcommand options"
.TP
\fB\-\-help\fR
Print help information
.TP
\fB\-\-mpis\fR
Prints cryptographic artifacts
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Writes to FILE or stdout if omitted
.TP
\fB\-\-session\-key\fR=\fISESSION\-KEY\fR
Decrypts an encrypted message using SESSION\-KEY
.TP
\fB\-\-version\fR
Print version information
.TP
\fB\-x\fR, \fB\-\-hex\fR
Prints a hexdump
.SH EXAMPLES
.PP

.PP
Prints the packets of a certificate
.PP
.nf
.RS
sq packet dump juliet.pgp
.RE
.fi
.PP

.PP
Prints cryptographic artifacts of a certificate
.PP
.nf
.RS
sq packet dump \-\-mpis juliet.pgp
.RE
.fi
.PP

.PP
Prints a hexdump of a certificate
.PP
.nf
.RS
sq packet dump \-\-hex juliet.pgp
.RE
.fi
.PP

.PP
Prints the packets of an encrypted message
.PP
.nf
.RS
sq packet dump \-\-session\-key AAAABBBBCCCC... ciphertext.pgp
.RE
.fi
.SH "SEE ALSO"
.nh
\fBsq\fR(1).
.hy
.PP
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.SH VERSION
0.28.0 (sequoia\-openpgp 1.13.0, using Nettle)
