.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH SQ 1 0.28.0 Sequoia-PGP "User Commands"
.SH NAME
sq revoke subkey \- Revoke a subkey
.SH SYNOPSIS
.br
\fBsq\fR [\fIGLOBAL OPTIONS\fR] \fBrevoke subkey\fR [\fIOPTIONS\fR] \fISUBKEY\fR \fIREASON\fR \fIMESSAGE\fR
.SH DESCRIPTION
Revokes a subkey.
.PP
Creates a revocation certificate for a subkey.
.PP
If "\-\-revocation\-file" is provided, then that key is used to create the signature.  If that key is different from the certificate being revoked, this creates a third\-party revocation.  This is normally only useful if the owner of the certificate designated the key to be a designated revoker.
.PP
If "\-\-revocation\-file" is not provided, then the certificate must include a certification\-capable key.

.SH OPTIONS
.SS "Global options"
.TP
\fB\-f\fR, \fB\-\-force\fR
Overwrites existing files
.TP
\fB\-\-help\fR
Print help information
.TP
\fB\-\-known\-notation\fR=\fINOTATION\fR
Adds NOTATION to the list of known notations
.TP
\fB\-\-output\-format\fR=\fIFORMAT\fR
Produces output in FORMAT, if possible
.TP
\fB\-\-output\-version\fR=\fIVERSION\fR
Produces output variant VERSION.
.TP
\fB\-\-version\fR
Print version information
.SS "Subcommand options"
.TP
\fB\-B\fR, \fB\-\-binary\fR
Emits binary data
.TP
\fB\-\-certificate\-file\fR=\fIFILE\fR
The certificate containing the subkey to revoke
.TP
\fB\-\-help\fR
Print help information
.TP
\fB\-\-notation\fR=\fINAME\fR
Adds a notation to the certification.
.TP
\fB\-\-private\-key\-store\fR=\fIKEY_STORE\fR
Provides parameters for private key store
.TP
\fB\-\-revocation\-file\fR=\fIKEY_FILE\fR
Signs the revocation certificate using the key in KEY_FILE
.TP
\fB\-t\fR, \fB\-\-time\fR=\fITIME\fR
Chooses keys valid at the specified time and sets the revocation certificate\*(Aqs creation time
.TP
\fB\-\-version\fR
Print version information
.SH "SEE ALSO"
.nh
\fBsq\fR(1).
.hy
.PP
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.SH VERSION
0.28.0 (sequoia\-openpgp 1.13.0, using Nettle)
