.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH SQ 1 0.28.0 Sequoia-PGP "User Commands"
.SH NAME
sq sign \- Signs messages or data files
.SH SYNOPSIS
.br
\fBsq\fR [\fIGLOBAL OPTIONS\fR] \fBsign\fR [\fIOPTIONS\fR] \fIFILE\fR
.SH DESCRIPTION
Signs messages or data files.
.PP
Creates signed messages or detached signatures.  Detached signatures
are often used to sign software packages.
.PP
The converse operation is "sq verify".
.PP


.SH OPTIONS
.SS "Global options"
.TP
\fB\-f\fR, \fB\-\-force\fR
Overwrites existing files
.TP
\fB\-\-help\fR
Print help information
.TP
\fB\-\-known\-notation\fR=\fINOTATION\fR
Adds NOTATION to the list of known notations
.TP
\fB\-\-output\-format\fR=\fIFORMAT\fR
Produces output in FORMAT, if possible
.TP
\fB\-\-output\-version\fR=\fIVERSION\fR
Produces output variant VERSION.
.TP
\fB\-\-version\fR
Print version information
.SS "Subcommand options"
.TP
\fB\-B\fR, \fB\-\-binary\fR
Emits binary data
.TP
\fB\-a\fR, \fB\-\-append\fR
Appends a signature to existing signature
.TP
\fB\-\-cleartext\-signature\fR
Creates a cleartext signature
.TP
\fB\-\-detached\fR
Creates a detached signature
.TP
\fB\-\-help\fR
Print help information
.TP
\fB\-\-merge\fR=\fISIGNED\-MESSAGE\fR
Merges signatures from the input and SIGNED\-MESSAGE
.TP
\fB\-n\fR, \fB\-\-notarize\fR
Signs a message and all existing signatures
.TP
\fB\-\-notation\fR=\fINAME\fR
Adds a notation to the certification.
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Writes to FILE or stdout if omitted
.TP
\fB\-\-private\-key\-store\fR=\fIKEY_STORE\fR
Provides parameters for private key store
.TP
\fB\-\-signer\-file\fR=\fIKEY_FILE\fR
Signs the message using the key in KEY_FILE
.TP
\fB\-t\fR, \fB\-\-time\fR=\fITIME\fR
Chooses keys valid at the specified time and sets the signature\*(Aqs creation time
.TP
\fB\-\-version\fR
Print version information
.SH EXAMPLES
.PP

.PP
Create a signed message
.PP
.nf
.RS
sq sign \-\-signer\-file juliet.pgp message.txt
.RE
.fi
.PP

.PP
Create a detached signature
.PP
.nf
.RS
sq sign \-\-detached \-\-signer\-file juliet.pgp message.txt
.RE
.fi
.SH "SEE ALSO"
.nh
\fBsq\fR(1).
.hy
.PP
For the full documentation see <https://docs.sequoia\-pgp.org/sq/>.
.SH VERSION
0.28.0 (sequoia\-openpgp 1.13.0, using Nettle)
